global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "accounting-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["accounting:8000"]

  - job_name: "inventory-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["inventory:8000"]

  - job_name: "pos-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["pos:8000"]

  - job_name: "hrms-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["hrms-service:8000"]

  - job_name: "intelligence-service"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["intelligence-service:8000"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
